name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # LINE Login (เวอร์ชันที่มีจริง)
  flutter_line_sdk: ^2.6.1

  # Google Login
  google_sign_in: ^6.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # ตัวอย่างใส่ assets (ถ้ามี)
  assets: # <--- ลบ # และเว้นวรรค 2 ช่อง ให้ตรงกับ uses-material-design
    - assets/ # <--- เพิ่ม assets/ และเว้นวรรค 4 ช่อง
  #   - images/

  # ตัวอย่างใส่ custom fonts (ถ้ามี)
  # fonts:
  #   - family: Roboto
  #     fonts:
  #       - asset: fonts/Roboto-Regular.ttf