name: flutter_application_1
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
      # 🌟 เพิ่มบรรทัดนี้
  shared_preferences: ^2.2.2 # หรือเวอร์ชันล่าสุด
  http: ^1.2.1

  # iOS-style icons
  cupertino_icons: ^1.0.8

  # LINE Login (เวอร์ชันที่มีจริง)
  flutter_line_sdk: ^2.6.1
  fl_chart: ^0.66.0

  # Google Login
  google_sign_in: ^6.1.6


dev_dependencies:
  flutter_test:
    sdk: flutter

  # Recommended lints
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/
