// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIBrg5TLDvQY6Ya9yMl1c8B3bsoFlXEKE',
    appId: '1:756271821434:web:0b22a5de41c3', // Simplified web appId as it wasn't provided, should be fine for now
    messagingSenderId: '756271821434',
    projectId: 'financecare-bca58',
    authDomain: 'financecare-bca58.firebaseapp.com',
    storageBucket: 'financecare-bca58.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIBrg5TLDvQY6Ya9yMl1c8B3bsoFlXEKE',
    appId: '1:756271821434:android:8f60c830ccc522a5de41c3',
    messagingSenderId: '756271821434',
    projectId: 'financecare-bca58',
    storageBucket: 'financecare-bca58.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIBrg5TLDvQY6Ya9yMl1c8B3bsoFlXEKE',
    appId: '1:756271821434:ios:0aec7892649102c6ade654',
    messagingSenderId: '756271821434',
    projectId: 'financecare-bca58',
    storageBucket: 'financecare-bca58.firebasestorage.app',
    iosBundleId: 'com.example.financeCare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB2BTitx8KGd3qmlXLZlRC5N7hmUYCjwwU',
    appId: '1:574118687805:ios:0aec7892649102c6ade654',
    messagingSenderId: '574118687805',
    projectId: 'financecare-ccc27',
    storageBucket: 'financecare-ccc27.firebasestorage.app',
    androidClientId: '574118687805-pjorecukb9lr507397v0fptenn6j6p11.apps.googleusercontent.com',
    iosClientId: '574118687805-69osb1lfvms1te7bdaeqgm8tp87lab14.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBfk4nE21_IO4Z7LSavlDHu1rXCWhUnmcI',
    appId: '1:574118687805:web:08e6e7e8f4c3168bade654',
    messagingSenderId: '574118687805',
    projectId: 'financecare-ccc27',
    authDomain: 'financecare-ccc27.firebaseapp.com',
    storageBucket: 'financecare-ccc27.firebasestorage.app',
    measurementId: 'G-V7FDERYK6B',
  );
}
